#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Armor_Colonist_Base

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Armor_Colonist_Base.Armor_Colonist_Base_C
// 0x0000 (0x0370 - 0x0370)
class UArmor_Colonist_Base_C : public UArmorSet
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Armor_Colonist_Base_C">();
	}
	static class UArmor_Colonist_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArmor_Colonist_Base_C>();
	}
};
static_assert(alignof(UArmor_Colonist_Base_C) == 0x000008, "Wrong alignment on UArmor_Colonist_Base_C");
static_assert(sizeof(UArmor_Colonist_Base_C) == 0x000370, "Wrong size on UArmor_Colonist_Base_C");

}

