#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Armor_CorpUnitCommander_CP_T2

#include "Basic.hpp"

#include "Armor_CorpUnitCommander_T2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Armor_CorpUnitCommander_CP_T2.Armor_CorpUnitCommander_CP_T2_C
// 0x0000 (0x0370 - 0x0370)
class UArmor_CorpUnitCommander_CP_T2_C : public UArmor_CorpUnitCommander_T2_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Armor_CorpUnitCommander_CP_T2_C">();
	}
	static class UArmor_CorpUnitCommander_CP_T2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArmor_CorpUnitCommander_CP_T2_C>();
	}
};
static_assert(alignof(UArmor_CorpUnitCommander_CP_T2_C) == 0x000008, "Wrong alignment on UArmor_CorpUnitCommander_CP_T2_C");
static_assert(sizeof(UArmor_CorpUnitCommander_CP_T2_C) == 0x000370, "Wrong size on UArmor_CorpUnitCommander_CP_T2_C");

}

