#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Base_Robot_Hover

#include "Basic.hpp"

#include "Indiana_structs.hpp"
#include "Engine_structs.hpp"
#include "Base_Ai_Character_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Base_Robot_Hover.Base_Robot_Hover_C
// 0x0020 (0x0ED0 - 0x0EB0)
#pragma pack(push, 0x1)
class alignas(0x10) ABase_Robot_Hover_C : public ABase_Ai_Character_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Base_Robot_Hover_C;                 // 0x0EB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               VFX_Engine;                                        // 0x0EB8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UConversationRegisterComponent*         ConversationRegister;                              // 0x0EC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Base_Robot_Hover(int32 EntryPoint);
	void Death(class AActor* Instigator_0, const struct FCauseDamageInfo& CauseDamageInfo);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Base_Robot_Hover_C">();
	}
	static class ABase_Robot_Hover_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABase_Robot_Hover_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABase_Robot_Hover_C) == 0x000010, "Wrong alignment on ABase_Robot_Hover_C");
static_assert(sizeof(ABase_Robot_Hover_C) == 0x000ED0, "Wrong size on ABase_Robot_Hover_C");
static_assert(offsetof(ABase_Robot_Hover_C, UberGraphFrame_Base_Robot_Hover_C) == 0x000EB0, "Member 'ABase_Robot_Hover_C::UberGraphFrame_Base_Robot_Hover_C' has a wrong offset!");
static_assert(offsetof(ABase_Robot_Hover_C, VFX_Engine) == 0x000EB8, "Member 'ABase_Robot_Hover_C::VFX_Engine' has a wrong offset!");
static_assert(offsetof(ABase_Robot_Hover_C, ConversationRegister) == 0x000EC0, "Member 'ABase_Robot_Hover_C::ConversationRegister' has a wrong offset!");

}

