#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BeaconButton_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BeaconButton_BP.BeaconButton_BP_C
// 0x0000 (0x0B98 - 0x0B98)
class UBeaconButton_BP_C final : public UButtonBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BeaconButton_BP_C">();
	}
	static class UBeaconButton_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBeaconButton_BP_C>();
	}
};
static_assert(alignof(UBeaconButton_BP_C) == 0x000008, "Wrong alignment on UBeaconButton_BP_C");
static_assert(sizeof(UBeaconButton_BP_C) == 0x000B98, "Wrong size on UBeaconButton_BP_C");

}

