#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BossBar_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BossBar_BP.BossBar_BP_C
// 0x0010 (0x0390 - 0x0380)
class UBossBar_BP_C final : public UIndianaBossBar
{
public:
	class UWidgetAnimation*                       Hide;                                              // 0x0380(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Show;                                              // 0x0388(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	class UWidgetAnimation* GetShowAnimation();
	class UWidgetAnimation* GetHideAnimation();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BossBar_BP_C">();
	}
	static class UBossBar_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBossBar_BP_C>();
	}
};
static_assert(alignof(UBossBar_BP_C) == 0x000008, "Wrong alignment on UBossBar_BP_C");
static_assert(sizeof(UBossBar_BP_C) == 0x000390, "Wrong size on UBossBar_BP_C");
static_assert(offsetof(UBossBar_BP_C, Hide) == 0x000380, "Member 'UBossBar_BP_C::Hide' has a wrong offset!");
static_assert(offsetof(UBossBar_BP_C, Show) == 0x000388, "Member 'UBossBar_BP_C::Show' has a wrong offset!");

}

