#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Env_Res_Integrated_EndTable_02

#include "Basic.hpp"

#include "BP_Env_Res_Integrated_EndTable_01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Env_Res_Integrated_EndTable_02.BP_Env_Res_Integrated_EndTable_02_C
// 0x0000 (0x02C8 - 0x02C8)
class ABP_Env_Res_Integrated_EndTable_02_C final : public ABP_Env_Res_Integrated_EndTable_01_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Env_Res_Integrated_EndTable_02_C">();
	}
	static class ABP_Env_Res_Integrated_EndTable_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Env_Res_Integrated_EndTable_02_C>();
	}
};
static_assert(alignof(ABP_Env_Res_Integrated_EndTable_02_C) == 0x000008, "Wrong alignment on ABP_Env_Res_Integrated_EndTable_02_C");
static_assert(sizeof(ABP_Env_Res_Integrated_EndTable_02_C) == 0x0002C8, "Wrong size on ABP_Env_Res_Integrated_EndTable_02_C");

}

