#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BrokenVending_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function BrokenVending_BP.BrokenVending_BP_C.GetLightingConfig
// 0x0010 (0x0010 - 0x0000)
struct BrokenVending_BP_C_GetLightingConfig final
{
public:
	class UStaticMeshComponent*                   Mesh;                                              // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   MaterialSlot;                                      // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BrokenVending_BP_C_GetLightingConfig) == 0x000008, "Wrong alignment on BrokenVending_BP_C_GetLightingConfig");
static_assert(sizeof(BrokenVending_BP_C_GetLightingConfig) == 0x000010, "Wrong size on BrokenVending_BP_C_GetLightingConfig");
static_assert(offsetof(BrokenVending_BP_C_GetLightingConfig, Mesh) == 0x000000, "Member 'BrokenVending_BP_C_GetLightingConfig::Mesh' has a wrong offset!");
static_assert(offsetof(BrokenVending_BP_C_GetLightingConfig, MaterialSlot) == 0x000008, "Member 'BrokenVending_BP_C_GetLightingConfig::MaterialSlot' has a wrong offset!");

}

