#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CE_Chilled_PostProcess

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CE_Chilled_PostProcess.CE_Chilled_PostProcess_C
// 0x0008 (0x0210 - 0x0208)
class UCE_Chilled_PostProcess_C final : public UPostProcessStatusEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0208(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_CE_Chilled_PostProcess(int32 EntryPoint);
	void ReceiveApplyEffect(class AActor* Target, float Ratio, bool bRestoredFromSave);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CE_Chilled_PostProcess_C">();
	}
	static class UCE_Chilled_PostProcess_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCE_Chilled_PostProcess_C>();
	}
};
static_assert(alignof(UCE_Chilled_PostProcess_C) == 0x000008, "Wrong alignment on UCE_Chilled_PostProcess_C");
static_assert(sizeof(UCE_Chilled_PostProcess_C) == 0x000210, "Wrong size on UCE_Chilled_PostProcess_C");
static_assert(offsetof(UCE_Chilled_PostProcess_C, UberGraphFrame) == 0x000208, "Member 'UCE_Chilled_PostProcess_C::UberGraphFrame' has a wrong offset!");

}

