#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CE_MindControl_GhostDebuff

#include "Basic.hpp"

#include "EmptyStatusEffect_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CE_MindControl_GhostDebuff.CE_MindControl_GhostDebuff_C
// 0x0000 (0x0188 - 0x0188)
class UCE_MindControl_GhostDebuff_C final : public UEmptyStatusEffect_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CE_MindControl_GhostDebuff_C">();
	}
	static class UCE_MindControl_GhostDebuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCE_MindControl_GhostDebuff_C>();
	}
};
static_assert(alignof(UCE_MindControl_GhostDebuff_C) == 0x000008, "Wrong alignment on UCE_MindControl_GhostDebuff_C");
static_assert(sizeof(UCE_MindControl_GhostDebuff_C) == 0x000188, "Wrong size on UCE_MindControl_GhostDebuff_C");

}

