#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ComputerTerminalContainer_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ComputerTerminalContainer_BP.ComputerTerminalContainer_BP_C
// 0x0000 (0x0328 - 0x0328)
class UComputerTerminalContainer_BP_C final : public UComputerTerminalContainerWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ComputerTerminalContainer_BP_C">();
	}
	static class UComputerTerminalContainer_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UComputerTerminalContainer_BP_C>();
	}
};
static_assert(alignof(UComputerTerminalContainer_BP_C) == 0x000008, "Wrong alignment on UComputerTerminalContainer_BP_C");
static_assert(sizeof(UComputerTerminalContainer_BP_C) == 0x000328, "Wrong size on UComputerTerminalContainer_BP_C");

}

