#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CompanionSkillSummary

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CompanionSkillSummary.CompanionSkillSummary_C
// 0x0000 (0x0358 - 0x0358)
class UCompanionSkillSummary_C final : public UCompanionSkillSummary
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CompanionSkillSummary_C">();
	}
	static class UCompanionSkillSummary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCompanionSkillSummary_C>();
	}
};
static_assert(alignof(UCompanionSkillSummary_C) == 0x000008, "Wrong alignment on UCompanionSkillSummary_C");
static_assert(sizeof(UCompanionSkillSummary_C) == 0x000358, "Wrong size on UCompanionSkillSummary_C");

}

