#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CREA_Raptidon_WeaponAnimations

#include "Basic.hpp"

#include "CREA_WeaponAnimations_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CREA_Raptidon_WeaponAnimations.CREA_Raptidon_WeaponAnimations_C
// 0x0000 (0x02D0 - 0x02D0)
class UCREA_Raptidon_WeaponAnimations_C : public UCREA_WeaponAnimations_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CREA_Raptidon_WeaponAnimations_C">();
	}
	static class UCREA_Raptidon_WeaponAnimations_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCREA_Raptidon_WeaponAnimations_C>();
	}
};
static_assert(alignof(UCREA_Raptidon_WeaponAnimations_C) == 0x000008, "Wrong alignment on UCREA_Raptidon_WeaponAnimations_C");
static_assert(sizeof(UCREA_Raptidon_WeaponAnimations_C) == 0x0002D0, "Wrong size on UCREA_Raptidon_WeaponAnimations_C");

}

