#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dreg_Thug_F_LightAR

#include "Basic.hpp"

#include "Base_Dreg_Thug_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dreg_Thug_F_LightAR.Dreg_Thug_F_LightAR_C
// 0x0000 (0x0ED0 - 0x0ED0)
class ADreg_Thug_F_LightAR_C final : public ABase_Dreg_Thug_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Dreg_Thug_F_LightAR_C">();
	}
	static class ADreg_Thug_F_LightAR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADreg_Thug_F_LightAR_C>();
	}
};
static_assert(alignof(ADreg_Thug_F_LightAR_C) == 0x000010, "Wrong alignment on ADreg_Thug_F_LightAR_C");
static_assert(sizeof(ADreg_Thug_F_LightAR_C) == 0x000ED0, "Wrong size on ADreg_Thug_F_LightAR_C");

}

