#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Drug_Cleo_VeritysBreathInhalant

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Drug_Cleo_VeritysBreathInhalant.Drug_Cleo_VeritysBreathInhalant_C
// 0x0000 (0x0230 - 0x0230)
class UDrug_Cleo_VeritysBreathInhalant_C final : public UConsumableItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Drug_Cleo_VeritysBreathInhalant_C">();
	}
	static class UDrug_Cleo_VeritysBreathInhalant_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDrug_Cleo_VeritysBreathInhalant_C>();
	}
};
static_assert(alignof(UDrug_Cleo_VeritysBreathInhalant_C) == 0x000008, "Wrong alignment on UDrug_Cleo_VeritysBreathInhalant_C");
static_assert(sizeof(UDrug_Cleo_VeritysBreathInhalant_C) == 0x000230, "Wrong size on UDrug_Cleo_VeritysBreathInhalant_C");

}

