#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DST_Box_Shock_BP

#include "Basic.hpp"

#include "DST_Barrel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DST_Box_Shock_BP.DST_Box_Shock_BP_C
// 0x0000 (0x0570 - 0x0570)
class ADST_Box_Shock_BP_C final : public ADST_Barrel_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DST_Box_Shock_BP_C">();
	}
	static class ADST_Box_Shock_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADST_Box_Shock_BP_C>();
	}
};
static_assert(alignof(ADST_Box_Shock_BP_C) == 0x000008, "Wrong alignment on ADST_Box_Shock_BP_C");
static_assert(sizeof(ADST_Box_Shock_BP_C) == 0x000570, "Wrong size on ADST_Box_Shock_BP_C");

}

