#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EliteRich_09_Var1

#include "Basic.hpp"

#include "Armor_EliteRich_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EliteRich_09_Var1.EliteRich_09_Var1_C
// 0x0000 (0x0370 - 0x0370)
class UEliteRich_09_Var1_C final : public UArmor_EliteRich_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EliteRich_09_Var1_C">();
	}
	static class UEliteRich_09_Var1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEliteRich_09_Var1_C>();
	}
};
static_assert(alignof(UEliteRich_09_Var1_C) == 0x000008, "Wrong alignment on UEliteRich_09_Var1_C");
static_assert(sizeof(UEliteRich_09_Var1_C) == 0x000370, "Wrong size on UEliteRich_09_Var1_C");

}

