#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EXAM_Power_Regulator_Housing

#include "Basic.hpp"

#include "EXAM_Power_Regulator_Housing_classes.hpp"
#include "EXAM_Power_Regulator_Housing_parameters.hpp"


namespace SDK
{

// Function EXAM_Power_Regulator_Housing.EXAM_Power_Regulator_Housing_C.GetInteractLocString
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FLocString                       ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FLocString AEXAM_Power_Regulator_Housing_C::GetInteractLocString() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EXAM_Power_Regulator_Housing_C", "GetInteractLocString");

	Params::EXAM_Power_Regulator_Housing_C_GetInteractLocString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EXAM_Power_Regulator_Housing.EXAM_Power_Regulator_Housing_C.GetInteraction
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FInteractionDescription          Description                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)
// struct FInteractPayload                 Payload                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   InteractDistance                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionType                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EInteractionType AEXAM_Power_Regulator_Housing_C::GetInteraction(const struct FInteractionDescription& Description, const struct FInteractPayload& Payload, float InteractDistance) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EXAM_Power_Regulator_Housing_C", "GetInteraction");

	Params::EXAM_Power_Regulator_Housing_C_GetInteraction Parms{};

	Parms.Description = std::move(Description);
	Parms.Payload = std::move(Payload);
	Parms.InteractDistance = InteractDistance;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

