#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FelixOutfit_Generic

#include "Basic.hpp"

#include "FelixOutfit_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FelixOutfit_Generic.FelixOutfit_Generic_C
// 0x0000 (0x0370 - 0x0370)
class UFelixOutfit_Generic_C final : public UFelixOutfit_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FelixOutfit_Generic_C">();
	}
	static class UFelixOutfit_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFelixOutfit_Generic_C>();
	}
};
static_assert(alignof(UFelixOutfit_Generic_C) == 0x000008, "Wrong alignment on UFelixOutfit_Generic_C");
static_assert(sizeof(UFelixOutfit_Generic_C) == 0x000370, "Wrong size on UFelixOutfit_Generic_C");

}

