#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GLB_NavKey_Stellar_Bay

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GLB_NavKey_Stellar_Bay.GLB_NavKey_Stellar_Bay_C
// 0x0000 (0x01D0 - 0x01D0)
class UGLB_NavKey_Stellar_Bay_C final : public UQuestItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GLB_NavKey_Stellar_Bay_C">();
	}
	static class UGLB_NavKey_Stellar_Bay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGLB_NavKey_Stellar_Bay_C>();
	}
};
static_assert(alignof(UGLB_NavKey_Stellar_Bay_C) == 0x000008, "Wrong alignment on UGLB_NavKey_Stellar_Bay_C");
static_assert(sizeof(UGLB_NavKey_Stellar_Bay_C) == 0x0001D0, "Wrong size on UGLB_NavKey_Stellar_Bay_C");

}

