#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Helmet_CorpRecruit_UDL_T2

#include "Basic.hpp"

#include "Helmet_CorpRecruit_T2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Helmet_CorpRecruit_UDL_T2.Helmet_CorpRecruit_UDL_T2_C
// 0x0000 (0x02B0 - 0x02B0)
class UHelmet_CorpRecruit_UDL_T2_C : public UHelmet_CorpRecruit_T2_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Helmet_CorpRecruit_UDL_T2_C">();
	}
	static class UHelmet_CorpRecruit_UDL_T2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHelmet_CorpRecruit_UDL_T2_C>();
	}
};
static_assert(alignof(UHelmet_CorpRecruit_UDL_T2_C) == 0x000008, "Wrong alignment on UHelmet_CorpRecruit_UDL_T2_C");
static_assert(sizeof(UHelmet_CorpRecruit_UDL_T2_C) == 0x0002B0, "Wrong size on UHelmet_CorpRecruit_UDL_T2_C");

}

