#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Imp_Shovel_Weapon

#include "Basic.hpp"

#include "Imp_Shovel_Weapon_classes.hpp"
#include "Imp_Shovel_Weapon_parameters.hpp"


namespace SDK
{

// Function Imp_Shovel_Weapon.Imp_Shovel_Weapon_C.ReceiveBeginPlay
// (BlueprintCallable, BlueprintEvent)

void UImp_Shovel_Weapon_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Imp_Shovel_Weapon_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Imp_Shovel_Weapon.Imp_Shovel_Weapon_C.ReceiveActorBeginOverlap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UImp_Shovel_Weapon_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Imp_Shovel_Weapon_C", "ReceiveActorBeginOverlap");

	Params::Imp_Shovel_Weapon_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Imp_Shovel_Weapon.Imp_Shovel_Weapon_C.ReceiveTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UImp_Shovel_Weapon_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Imp_Shovel_Weapon_C", "ReceiveTick");

	Params::Imp_Shovel_Weapon_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Imp_Shovel_Weapon.Imp_Shovel_Weapon_C.ExecuteUbergraph_Imp_Shovel_Weapon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UImp_Shovel_Weapon_C::ExecuteUbergraph_Imp_Shovel_Weapon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Imp_Shovel_Weapon_C", "ExecuteUbergraph_Imp_Shovel_Weapon");

	Params::Imp_Shovel_Weapon_C_ExecuteUbergraph_Imp_Shovel_Weapon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

