#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IndianaPlayerController_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IndianaPlayerController_BP.IndianaPlayerController_BP_C
// 0x0000 (0x0680 - 0x0680)
class AIndianaPlayerController_BP_C final : public AIndianaPlayerController
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IndianaPlayerController_BP_C">();
	}
	static class AIndianaPlayerController_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIndianaPlayerController_BP_C>();
	}
};
static_assert(alignof(AIndianaPlayerController_BP_C) == 0x000008, "Wrong alignment on AIndianaPlayerController_BP_C");
static_assert(sizeof(AIndianaPlayerController_BP_C) == 0x000680, "Wrong size on AIndianaPlayerController_BP_C");

}

