#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Junk_Bracelet

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Junk_Bracelet.Junk_Bracelet_C
// 0x0000 (0x0140 - 0x0140)
class UJunk_Bracelet_C final : public UResourceItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Junk_Bracelet_C">();
	}
	static class UJunk_Bracelet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJunk_Bracelet_C>();
	}
};
static_assert(alignof(UJunk_Bracelet_C) == 0x000008, "Wrong alignment on UJunk_Bracelet_C");
static_assert(sizeof(UJunk_Bracelet_C) == 0x000140, "Wrong size on UJunk_Bracelet_C");

}

