#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Laborer_02_Var1

#include "Basic.hpp"

#include "Armor_Laborer_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Laborer_02_Var1.Laborer_02_Var1_C
// 0x0000 (0x0370 - 0x0370)
class ULaborer_02_Var1_C final : public UArmor_Laborer_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Laborer_02_Var1_C">();
	}
	static class ULaborer_02_Var1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULaborer_02_Var1_C>();
	}
};
static_assert(alignof(ULaborer_02_Var1_C) == 0x000008, "Wrong alignment on ULaborer_02_Var1_C");
static_assert(sizeof(ULaborer_02_Var1_C) == 0x000370, "Wrong size on ULaborer_02_Var1_C");

}

