#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: META_SmartDodge_NoCooldown

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass META_SmartDodge_NoCooldown.META_SmartDodge_NoCooldown_C
// 0x0000 (0x0058 - 0x0058)
class UMETA_SmartDodge_NoCooldown_C final : public UDecisionTree_Dodge
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"META_SmartDodge_NoCooldown_C">();
	}
	static class UMETA_SmartDodge_NoCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMETA_SmartDodge_NoCooldown_C>();
	}
};
static_assert(alignof(UMETA_SmartDodge_NoCooldown_C) == 0x000008, "Wrong alignment on UMETA_SmartDodge_NoCooldown_C");
static_assert(sizeof(UMETA_SmartDodge_NoCooldown_C) == 0x000058, "Wrong size on UMETA_SmartDodge_NoCooldown_C");

}

