#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NyokaOutfit_Generic

#include "Basic.hpp"

#include "NyokaOutfit_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NyokaOutfit_Generic.NyokaOutfit_Generic_C
// 0x0000 (0x0370 - 0x0370)
class UNyokaOutfit_Generic_C final : public UNyokaOutfit_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NyokaOutfit_Generic_C">();
	}
	static class UNyokaOutfit_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNyokaOutfit_Generic_C>();
	}
};
static_assert(alignof(UNyokaOutfit_Generic_C) == 0x000008, "Wrong alignment on UNyokaOutfit_Generic_C");
static_assert(sizeof(UNyokaOutfit_Generic_C) == 0x000370, "Wrong size on UNyokaOutfit_Generic_C");

}

