#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerPerkListRow_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerPerkListRow_BP.PlayerPerkListRow_BP_C
// 0x0008 (0x0430 - 0x0428)
class UPlayerPerkListRow_BP_C final : public UPerksListRowWidget
{
public:
	class UImage*                                 PerkAnchor;                                        // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerPerkListRow_BP_C">();
	}
	static class UPlayerPerkListRow_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerPerkListRow_BP_C>();
	}
};
static_assert(alignof(UPlayerPerkListRow_BP_C) == 0x000008, "Wrong alignment on UPlayerPerkListRow_BP_C");
static_assert(sizeof(UPlayerPerkListRow_BP_C) == 0x000430, "Wrong size on UPlayerPerkListRow_BP_C");
static_assert(offsetof(UPlayerPerkListRow_BP_C, PerkAnchor) == 0x000428, "Member 'UPlayerPerkListRow_BP_C::PerkAnchor' has a wrong offset!");

}

