#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PRESET_Ivy_SlowerLeaves_BP

#include "Basic.hpp"

#include "PRESET_Ivy1_Var3_BP_0_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PRESET_Ivy_SlowerLeaves_BP.PRESET_Ivy_SlowerLeaves_BP_C
// 0x0000 (0x0530 - 0x0530)
class APRESET_Ivy_SlowerLeaves_BP_C final : public PRESET_Ivy1_Var3_BP_0::APRESET_Ivy1_Var3_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PRESET_Ivy_SlowerLeaves_BP_C">();
	}
	static class APRESET_Ivy_SlowerLeaves_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APRESET_Ivy_SlowerLeaves_BP_C>();
	}
};
static_assert(alignof(APRESET_Ivy_SlowerLeaves_BP_C) == 0x000008, "Wrong alignment on APRESET_Ivy_SlowerLeaves_BP_C");
static_assert(sizeof(APRESET_Ivy_SlowerLeaves_BP_C) == 0x000530, "Wrong size on APRESET_Ivy_SlowerLeaves_BP_C");

}

