#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Raptidon_Melee_TP_Visuals

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Raptidon_Melee_TP_Visuals.Raptidon_Melee_TP_Visuals_C
// 0x0000 (0x0248 - 0x0248)
class URaptidon_Melee_TP_Visuals_C final : public UPrimaryWeaponVisuals
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Raptidon_Melee_TP_Visuals_C">();
	}
	static class URaptidon_Melee_TP_Visuals_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URaptidon_Melee_TP_Visuals_C>();
	}
};
static_assert(alignof(URaptidon_Melee_TP_Visuals_C) == 0x000008, "Wrong alignment on URaptidon_Melee_TP_Visuals_C");
static_assert(sizeof(URaptidon_Melee_TP_Visuals_C) == 0x000248, "Wrong size on URaptidon_Melee_TP_Visuals_C");

}

