#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Science_Skill

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Science_Skill.Science_Skill_C
// 0x0000 (0x0078 - 0x0078)
class UScience_Skill_C final : public UScienceSkill
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Science_Skill_C">();
	}
	static class UScience_Skill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScience_Skill_C>();
	}
};
static_assert(alignof(UScience_Skill_C) == 0x000008, "Wrong alignment on UScience_Skill_C");
static_assert(sizeof(UScience_Skill_C) == 0x000078, "Wrong size on UScience_Skill_C");

}

