#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillAdjustment_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SkillAdjustment_BP.SkillAdjustment_BP_C
// 0x0000 (0x0340 - 0x0340)
class USkillAdjustment_BP_C final : public USkillAdjustment
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SkillAdjustment_BP_C">();
	}
	static class USkillAdjustment_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkillAdjustment_BP_C>();
	}
};
static_assert(alignof(USkillAdjustment_BP_C) == 0x000008, "Wrong alignment on USkillAdjustment_BP_C");
static_assert(sizeof(USkillAdjustment_BP_C) == 0x000340, "Wrong size on USkillAdjustment_BP_C");

}

