#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Spacer_04_Var5

#include "Basic.hpp"

#include "Spacer_Armor_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Spacer_04_Var5.Spacer_04_Var5_C
// 0x0000 (0x0370 - 0x0370)
class USpacer_04_Var5_C final : public USpacer_Armor_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Spacer_04_Var5_C">();
	}
	static class USpacer_04_Var5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpacer_04_Var5_C>();
	}
};
static_assert(alignof(USpacer_04_Var5_C) == 0x000008, "Wrong alignment on USpacer_04_Var5_C");
static_assert(sizeof(USpacer_04_Var5_C) == 0x000370, "Wrong size on USpacer_04_Var5_C");

}

