#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatsPerkSummaryEntry_BP1

#include "Basic.hpp"

#include "StatsPerkSummaryEntry_BP1_classes.hpp"
#include "StatsPerkSummaryEntry_BP1_parameters.hpp"


namespace SDK
{

// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.ExecuteUbergraph_StatsPerkSummaryEntry_BP1
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStatsPerkSummaryEntry_BP1_C::ExecuteUbergraph_StatsPerkSummaryEntry_BP1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "ExecuteUbergraph_StatsPerkSummaryEntry_BP1");

	Params::StatsPerkSummaryEntry_BP1_C_ExecuteUbergraph_StatsPerkSummaryEntry_BP1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature");

	Params::StatsPerkSummaryEntry_BP1_C_BndEvt__Button_K2Node_ComponentBoundEvent_3_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature");

	Params::StatsPerkSummaryEntry_BP1_C_BndEvt__Button_K2Node_ComponentBoundEvent_2_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_1_NoParamMCD__DelegateSignature
// (BlueprintEvent)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_1_NoParamMCD__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_1_NoParamMCD__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature");

	Params::StatsPerkSummaryEntry_BP1_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FComponentEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature(const struct FComponentEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature");

	Params::StatsPerkSummaryEntry_BP1_C_BndEvt__Button_K2Node_ComponentBoundEvent_15_ComponentEventMCD__DelegateSignature Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function StatsPerkSummaryEntry_BP1.StatsPerkSummaryEntry_BP1_C.BndEvt__Button_K2Node_ComponentBoundEvent_8_NoParamMCD__DelegateSignature
// (BlueprintEvent)

void UStatsPerkSummaryEntry_BP1_C::BndEvt__Button_K2Node_ComponentBoundEvent_8_NoParamMCD__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsPerkSummaryEntry_BP1_C", "BndEvt__Button_K2Node_ComponentBoundEvent_8_NoParamMCD__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

