#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatsPerkListRow_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass StatsPerkListRow_BP.StatsPerkListRow_BP_C
// 0x0008 (0x0430 - 0x0428)
class UStatsPerkListRow_BP_C final : public UPerksListRowWidget
{
public:
	class UImage*                                 PerkAnchor;                                        // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StatsPerkListRow_BP_C">();
	}
	static class UStatsPerkListRow_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStatsPerkListRow_BP_C>();
	}
};
static_assert(alignof(UStatsPerkListRow_BP_C) == 0x000008, "Wrong alignment on UStatsPerkListRow_BP_C");
static_assert(sizeof(UStatsPerkListRow_BP_C) == 0x000430, "Wrong size on UStatsPerkListRow_BP_C");
static_assert(offsetof(UStatsPerkListRow_BP_C, PerkAnchor) == 0x000428, "Member 'UStatsPerkListRow_BP_C::PerkAnchor' has a wrong offset!");

}

