#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SwitchToRangedWeaponPreferUnlimitedRange

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SwitchToRangedWeaponPreferUnlimitedRange.SwitchToRangedWeaponPreferUnlimitedRange_C
// 0x0000 (0x0048 - 0x0048)
class USwitchToRangedWeaponPreferUnlimitedRange_C final : public UDecisionTree_CombinedRequests
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SwitchToRangedWeaponPreferUnlimitedRange_C">();
	}
	static class USwitchToRangedWeaponPreferUnlimitedRange_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USwitchToRangedWeaponPreferUnlimitedRange_C>();
	}
};
static_assert(alignof(USwitchToRangedWeaponPreferUnlimitedRange_C) == 0x000008, "Wrong alignment on USwitchToRangedWeaponPreferUnlimitedRange_C");
static_assert(sizeof(USwitchToRangedWeaponPreferUnlimitedRange_C) == 0x000048, "Wrong size on USwitchToRangedWeaponPreferUnlimitedRange_C");

}

