#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: T_0411_CnPFactory_Exterior

#include "Basic.hpp"

#include "T_Generic_Friendly_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass T_0411_CnPFactory_Exterior.T_0411_CnPFactory_Exterior_C
// 0x0000 (0x0238 - 0x0238)
class UT_0411_CnPFactory_Exterior_C final : public UT_Generic_Friendly_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"T_0411_CnPFactory_Exterior_C">();
	}
	static class UT_0411_CnPFactory_Exterior_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UT_0411_CnPFactory_Exterior_C>();
	}
};
static_assert(alignof(UT_0411_CnPFactory_Exterior_C) == 0x000008, "Wrong alignment on UT_0411_CnPFactory_Exterior_C");
static_assert(sizeof(UT_0411_CnPFactory_Exterior_C) == 0x000238, "Wrong size on UT_0411_CnPFactory_Exterior_C");

}

