#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheHope

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TheHope.TheHope_C
// 0x0000 (0x0200 - 0x0200)
class UTheHope_C final : public UFactionData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TheHope_C">();
	}
	static class UTheHope_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTheHope_C>();
	}
};
static_assert(alignof(UTheHope_C) == 0x000008, "Wrong alignment on UTheHope_C");
static_assert(sizeof(UTheHope_C) == 0x000200, "Wrong size on UTheHope_C");

}

