#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBUpgradePage_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBUpgradePage_BP.WBUpgradePage_BP_C
// 0x0008 (0x0430 - 0x0428)
class UWBUpgradePage_BP_C final : public UWBUpgradePageWidget
{
public:
	class USizeBox*                               PagesSizeBox;                                      // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBUpgradePage_BP_C">();
	}
	static class UWBUpgradePage_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBUpgradePage_BP_C>();
	}
};
static_assert(alignof(UWBUpgradePage_BP_C) == 0x000008, "Wrong alignment on UWBUpgradePage_BP_C");
static_assert(sizeof(UWBUpgradePage_BP_C) == 0x000430, "Wrong size on UWBUpgradePage_BP_C");
static_assert(offsetof(UWBUpgradePage_BP_C, PagesSizeBox) == 0x000428, "Member 'UWBUpgradePage_BP_C::PagesSizeBox' has a wrong offset!");

}

