#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponSFX_GunsMinusLong_Plasma_Joch

#include "Basic.hpp"

#include "_WeaponSFX_GunsMinusLong_PlasmaRifle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponSFX_Guns-Long_Plasma_Joch.WeaponSFX_Guns-Long_Plasma_Joch_C
// 0x0000 (0x0200 - 0x0200)
class UWeaponSFX_GunsMinusLong_Plasma_Joch_C final : public U_WeaponSFX_GunsMinusLong_PlasmaRifle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeaponSFX_Guns-Long_Plasma_Joch_C">();
	}
	static class UWeaponSFX_GunsMinusLong_Plasma_Joch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeaponSFX_GunsMinusLong_Plasma_Joch_C>();
	}
};
static_assert(alignof(UWeaponSFX_GunsMinusLong_Plasma_Joch_C) == 0x000008, "Wrong alignment on UWeaponSFX_GunsMinusLong_Plasma_Joch_C");
static_assert(sizeof(UWeaponSFX_GunsMinusLong_Plasma_Joch_C) == 0x000200, "Wrong size on UWeaponSFX_GunsMinusLong_Plasma_Joch_C");

}

