#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: __Door_Sound_Generic

#include "Basic.hpp"

#include "Indiana_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass __Door_Sound_Generic.__Door_Sound_Generic_C
// 0x0008 (0x01A8 - 0x01A0)
class U__Door_Sound_Generic_C : public UOCLAudioComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph___Door_Sound_Generic(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"__Door_Sound_Generic_C">();
	}
	static class U__Door_Sound_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<U__Door_Sound_Generic_C>();
	}
};
static_assert(alignof(U__Door_Sound_Generic_C) == 0x000008, "Wrong alignment on U__Door_Sound_Generic_C");
static_assert(sizeof(U__Door_Sound_Generic_C) == 0x0001A8, "Wrong size on U__Door_Sound_Generic_C");
static_assert(offsetof(U__Door_Sound_Generic_C, UberGraphFrame) == 0x0001A0, "Member 'U__Door_Sound_Generic_C::UberGraphFrame' has a wrong offset!");

}

