#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: __WeaponSFX_Guns_Hand

#include "Basic.hpp"

#include "___WeaponSFX_Ranged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass __WeaponSFX_Guns-Hand.__WeaponSFX_Guns-Hand_C
// 0x0000 (0x0200 - 0x0200)
class U__WeaponSFX_Guns_Hand_C : public U___WeaponSFX_Ranged_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"__WeaponSFX_Guns-Hand_C">();
	}
	static class U__WeaponSFX_Guns_Hand_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<U__WeaponSFX_Guns_Hand_C>();
	}
};
static_assert(alignof(U__WeaponSFX_Guns_Hand_C) == 0x000008, "Wrong alignment on U__WeaponSFX_Guns_Hand_C");
static_assert(sizeof(U__WeaponSFX_Guns_Hand_C) == 0x000200, "Wrong size on U__WeaponSFX_Guns_Hand_C");

}

