#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArmorMod_Skill_StealthKit

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ArmorMod_Skill_StealthKit.ArmorMod_Skill_StealthKit_C
// 0x0000 (0x0260 - 0x0260)
class UArmorMod_Skill_StealthKit_C final : public UArmorModDampening
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ArmorMod_Skill_StealthKit_C">();
	}
	static class UArmorMod_Skill_StealthKit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArmorMod_Skill_StealthKit_C>();
	}
};
static_assert(alignof(UArmorMod_Skill_StealthKit_C) == 0x000008, "Wrong alignment on UArmorMod_Skill_StealthKit_C");
static_assert(sizeof(UArmorMod_Skill_StealthKit_C) == 0x000260, "Wrong size on UArmorMod_Skill_StealthKit_C");

}

