#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BeaconEntry_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BeaconEntry_BP.BeaconEntry_BP_C
// 0x0000 (0x0358 - 0x0358)
class UBeaconEntry_BP_C final : public UBeaconMapEntryWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BeaconEntry_BP_C">();
	}
	static class UBeaconEntry_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBeaconEntry_BP_C>();
	}
};
static_assert(alignof(UBeaconEntry_BP_C) == 0x000008, "Wrong alignment on UBeaconEntry_BP_C");
static_assert(sizeof(UBeaconEntry_BP_C) == 0x000358, "Wrong size on UBeaconEntry_BP_C");

}

