#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BossBar_BP

#include "Basic.hpp"

#include "BossBar_BP_classes.hpp"
#include "BossBar_BP_parameters.hpp"


namespace SDK
{

// Function BossBar_BP.BossBar_BP_C.GetShowAnimation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidgetAnimation* UBossBar_BP_C::GetShowAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BossBar_BP_C", "GetShowAnimation");

	Params::BossBar_BP_C_GetShowAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BossBar_BP.BossBar_BP_C.GetHideAnimation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidgetAnimation* UBossBar_BP_C::GetHideAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BossBar_BP_C", "GetHideAnimation");

	Params::BossBar_BP_C_GetHideAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

