#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Button_MoreCompanions_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Button_MoreCompanions_BP.Button_MoreCompanions_BP_C
// 0x0000 (0x0B98 - 0x0B98)
class UButton_MoreCompanions_BP_C final : public UButtonBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button_MoreCompanions_BP_C">();
	}
	static class UButton_MoreCompanions_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton_MoreCompanions_BP_C>();
	}
};
static_assert(alignof(UButton_MoreCompanions_BP_C) == 0x000008, "Wrong alignment on UButton_MoreCompanions_BP_C");
static_assert(sizeof(UButton_MoreCompanions_BP_C) == 0x000B98, "Wrong size on UButton_MoreCompanions_BP_C");

}

