#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Canid_HowlDecisionTree

#include "Basic.hpp"

#include "Indiana_structs.hpp"
#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Canid_HowlDecisionTree.Canid_HowlDecisionTree_C
// 0x0000 (0x0030 - 0x0030)
class UCanid_HowlDecisionTree_C final : public UDecisionTree
{
public:
	TArray<class UDecisionTreeRequestData*> RunDecisionTree(class AIndianaAiCharacter* Owner, class FName EventType, class UAIEventInfo* EventInfo, EDecisionTreeRequestPriority* OutPriority);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Canid_HowlDecisionTree_C">();
	}
	static class UCanid_HowlDecisionTree_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCanid_HowlDecisionTree_C>();
	}
};
static_assert(alignof(UCanid_HowlDecisionTree_C) == 0x000008, "Wrong alignment on UCanid_HowlDecisionTree_C");
static_assert(sizeof(UCanid_HowlDecisionTree_C) == 0x000030, "Wrong size on UCanid_HowlDecisionTree_C");

}

