#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CE_IdleDisable

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CE_IdleDisable.CE_IdleDisable_C
// 0x0000 (0x01A0 - 0x01A0)
class UCE_IdleDisable_C final : public UIdleDisableStatusEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CE_IdleDisable_C">();
	}
	static class UCE_IdleDisable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCE_IdleDisable_C>();
	}
};
static_assert(alignof(UCE_IdleDisable_C) == 0x000008, "Wrong alignment on UCE_IdleDisable_C");
static_assert(sizeof(UCE_IdleDisable_C) == 0x0001A0, "Wrong size on UCE_IdleDisable_C");

}

