#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CE_Phobia

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CE_Phobia.CE_Phobia_C
// 0x0000 (0x01B8 - 0x01B8)
class UCE_Phobia_C : public UMultiStatusEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CE_Phobia_C">();
	}
	static class UCE_Phobia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCE_Phobia_C>();
	}
};
static_assert(alignof(UCE_Phobia_C) == 0x000008, "Wrong alignment on UCE_Phobia_C");
static_assert(sizeof(UCE_Phobia_C) == 0x0001B8, "Wrong size on UCE_Phobia_C");

}

