#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Creature_Canid_Feral_Unique

#include "Basic.hpp"

#include "Creature_Canid_Feral_Unique_classes.hpp"
#include "Creature_Canid_Feral_Unique_parameters.hpp"


namespace SDK
{

// Function Creature_Canid_Feral_Unique.Creature_Canid_Feral_Unique_C.ExecuteUbergraph_Creature_Canid_Feral_Unique
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACreature_Canid_Feral_Unique_C::ExecuteUbergraph_Creature_Canid_Feral_Unique(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Creature_Canid_Feral_Unique_C", "ExecuteUbergraph_Creature_Canid_Feral_Unique");

	Params::Creature_Canid_Feral_Unique_C_ExecuteUbergraph_Creature_Canid_Feral_Unique Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Creature_Canid_Feral_Unique.Creature_Canid_Feral_Unique_C.BndEvt__CharacterDeath_K2Node_ComponentBoundEvent_3_ActorComponentActivatedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UActorComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bReset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACreature_Canid_Feral_Unique_C::BndEvt__CharacterDeath_K2Node_ComponentBoundEvent_3_ActorComponentActivatedSignature__DelegateSignature(class UActorComponent* Component, bool bReset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Creature_Canid_Feral_Unique_C", "BndEvt__CharacterDeath_K2Node_ComponentBoundEvent_3_ActorComponentActivatedSignature__DelegateSignature");

	Params::Creature_Canid_Feral_Unique_C_BndEvt__CharacterDeath_K2Node_ComponentBoundEvent_3_ActorComponentActivatedSignature__DelegateSignature Parms{};

	Parms.Component = Component;
	Parms.bReset = bReset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Creature_Canid_Feral_Unique.Creature_Canid_Feral_Unique_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACreature_Canid_Feral_Unique_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Creature_Canid_Feral_Unique_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

