#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Destructible_Abstract

#include "Basic.hpp"

#include "Destructible_Abstract_classes.hpp"
#include "Destructible_Abstract_parameters.hpp"


namespace SDK
{

// Function Destructible_Abstract.Destructible_Abstract_C.ExecuteUbergraph_Destructible_Abstract
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADestructible_Abstract_C::ExecuteUbergraph_Destructible_Abstract(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "ExecuteUbergraph_Destructible_Abstract");

	Params::Destructible_Abstract_C_ExecuteUbergraph_Destructible_Abstract Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Destructible_Abstract.Destructible_Abstract_C.OnDestructibleDestroyed_Event_Base
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADestructible_Abstract_C::OnDestructibleDestroyed_Event_Base(class AActor* Instigator_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "OnDestructibleDestroyed_Event_Base");

	Params::Destructible_Abstract_C_OnDestructibleDestroyed_Event_Base Parms{};

	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Destructible_Abstract.Destructible_Abstract_C.OnDestructibleDamaged_Event_Base
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADestructible_Abstract_C::OnDestructibleDamaged_Event_Base(class AActor* Instigator_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "OnDestructibleDamaged_Event_Base");

	Params::Destructible_Abstract_C_OnDestructibleDamaged_Event_Base Parms{};

	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Destructible_Abstract.Destructible_Abstract_C.OnDestructiblePristine_Event_Base
// (BlueprintCallable, BlueprintEvent)

void ADestructible_Abstract_C::OnDestructiblePristine_Event_Base()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "OnDestructiblePristine_Event_Base");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Destructible_Abstract.Destructible_Abstract_C.ReceiveDeployOrder
// (Event, Protected, BlueprintEvent)

void ADestructible_Abstract_C::ReceiveDeployOrder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "ReceiveDeployOrder");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Destructible_Abstract.Destructible_Abstract_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADestructible_Abstract_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Destructible_Abstract.Destructible_Abstract_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ADestructible_Abstract_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Destructible_Abstract_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

