#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DialogBoxWarning_BP

#include "Basic.hpp"

#include "DialogBoxWarning_BP_classes.hpp"
#include "DialogBoxWarning_BP_parameters.hpp"


namespace SDK
{

// Function DialogBoxWarning_BP.DialogBoxWarning_BP_C.ExecuteUbergraph_DialogBoxWarning_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDialogBoxWarning_BP_C::ExecuteUbergraph_DialogBoxWarning_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DialogBoxWarning_BP_C", "ExecuteUbergraph_DialogBoxWarning_BP");

	Params::DialogBoxWarning_BP_C_ExecuteUbergraph_DialogBoxWarning_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DialogBoxWarning_BP.DialogBoxWarning_BP_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDialogBoxWarning_BP_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DialogBoxWarning_BP_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

