#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Doctor

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Doctor.Doctor_C
// 0x0000 (0x0370 - 0x0370)
class UDoctor_C final : public UArmorSet
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Doctor_C">();
	}
	static class UDoctor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoctor_C>();
	}
};
static_assert(alignof(UDoctor_C) == 0x000008, "Wrong alignment on UDoctor_C");
static_assert(sizeof(UDoctor_C) == 0x000370, "Wrong size on UDoctor_C");

}

