#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Drink_Rizzo_SpectrumVodkaViolet

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Drink_Rizzo_SpectrumVodkaViolet.Drink_Rizzo_SpectrumVodkaViolet_C
// 0x0000 (0x0230 - 0x0230)
class UDrink_Rizzo_SpectrumVodkaViolet_C final : public UConsumableItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Drink_Rizzo_SpectrumVodkaViolet_C">();
	}
	static class UDrink_Rizzo_SpectrumVodkaViolet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDrink_Rizzo_SpectrumVodkaViolet_C>();
	}
};
static_assert(alignof(UDrink_Rizzo_SpectrumVodkaViolet_C) == 0x000008, "Wrong alignment on UDrink_Rizzo_SpectrumVodkaViolet_C");
static_assert(sizeof(UDrink_Rizzo_SpectrumVodkaViolet_C) == 0x000230, "Wrong size on UDrink_Rizzo_SpectrumVodkaViolet_C");

}

