#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ham_FlechetteGun_Weapon_T2

#include "Basic.hpp"

#include "Ham_FlechetteGun_Weapon_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ham_FlechetteGun_Weapon_T2.Ham_FlechetteGun_Weapon_T2_C
// 0x0000 (0x05D0 - 0x05D0)
class UHam_FlechetteGun_Weapon_T2_C final : public UHam_FlechetteGun_Weapon_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ham_FlechetteGun_Weapon_T2_C">();
	}
	static class UHam_FlechetteGun_Weapon_T2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHam_FlechetteGun_Weapon_T2_C>();
	}
};
static_assert(alignof(UHam_FlechetteGun_Weapon_T2_C) == 0x000008, "Wrong alignment on UHam_FlechetteGun_Weapon_T2_C");
static_assert(sizeof(UHam_FlechetteGun_Weapon_T2_C) == 0x0005D0, "Wrong size on UHam_FlechetteGun_Weapon_T2_C");

}

