#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoverBot_Gun_Weapon_Burst_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass HoverBot_Gun_Weapon_Burst_BP.HoverBot_Gun_Weapon_Burst_BP_C
// 0x0008 (0x05D8 - 0x05D0)
class UHoverBot_Gun_Weapon_Burst_BP_C final : public UWeapon
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_HoverBot_Gun_Weapon_Burst_BP(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HoverBot_Gun_Weapon_Burst_BP_C">();
	}
	static class UHoverBot_Gun_Weapon_Burst_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHoverBot_Gun_Weapon_Burst_BP_C>();
	}
};
static_assert(alignof(UHoverBot_Gun_Weapon_Burst_BP_C) == 0x000008, "Wrong alignment on UHoverBot_Gun_Weapon_Burst_BP_C");
static_assert(sizeof(UHoverBot_Gun_Weapon_Burst_BP_C) == 0x0005D8, "Wrong size on UHoverBot_Gun_Weapon_Burst_BP_C");
static_assert(offsetof(UHoverBot_Gun_Weapon_Burst_BP_C, UberGraphFrame) == 0x0005D0, "Member 'UHoverBot_Gun_Weapon_Burst_BP_C::UberGraphFrame' has a wrong offset!");

}

