#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HungerSpell_T1

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HungerSpell_T1.HungerSpell_T1_C
// 0x0000 (0x0190 - 0x0190)
class UHungerSpell_T1_C final : public USpell
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HungerSpell_T1_C">();
	}
	static class UHungerSpell_T1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHungerSpell_T1_C>();
	}
};
static_assert(alignof(UHungerSpell_T1_C) == 0x000010, "Wrong alignment on UHungerSpell_T1_C");
static_assert(sizeof(UHungerSpell_T1_C) == 0x000190, "Wrong size on UHungerSpell_T1_C");

}

