#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Imp_TossballStick_Weapon_T3

#include "Basic.hpp"

#include "Imp_TossballStick_Weapon_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Imp_TossballStick_Weapon_T3.Imp_TossballStick_Weapon_T3_C
// 0x0000 (0x05D8 - 0x05D8)
class UImp_TossballStick_Weapon_T3_C final : public UImp_TossballStick_Weapon_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Imp_TossballStick_Weapon_T3_C">();
	}
	static class UImp_TossballStick_Weapon_T3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UImp_TossballStick_Weapon_T3_C>();
	}
};
static_assert(alignof(UImp_TossballStick_Weapon_T3_C) == 0x000008, "Wrong alignment on UImp_TossballStick_Weapon_T3_C");
static_assert(sizeof(UImp_TossballStick_Weapon_T3_C) == 0x0005D8, "Wrong size on UImp_TossballStick_Weapon_T3_C");

}

