#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IndianaGameInstance_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IndianaGameInstance_BP.IndianaGameInstance_BP_C
// 0x0000 (0x0D70 - 0x0D70)
class UIndianaGameInstance_BP_C final : public UIndianaGameInstance
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IndianaGameInstance_BP_C">();
	}
	static class UIndianaGameInstance_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIndianaGameInstance_BP_C>();
	}
};
static_assert(alignof(UIndianaGameInstance_BP_C) == 0x000010, "Wrong alignment on UIndianaGameInstance_BP_C");
static_assert(sizeof(UIndianaGameInstance_BP_C) == 0x000D70, "Wrong size on UIndianaGameInstance_BP_C");

}

