#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: INX2_CE_BrownVodkaBlues

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass INX2_CE_BrownVodkaBlues.INX2_CE_BrownVodkaBlues_C
// 0x0000 (0x01B8 - 0x01B8)
class UINX2_CE_BrownVodkaBlues_C final : public UMultiStatusEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"INX2_CE_BrownVodkaBlues_C">();
	}
	static class UINX2_CE_BrownVodkaBlues_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UINX2_CE_BrownVodkaBlues_C>();
	}
};
static_assert(alignof(UINX2_CE_BrownVodkaBlues_C) == 0x000008, "Wrong alignment on UINX2_CE_BrownVodkaBlues_C");
static_assert(sizeof(UINX2_CE_BrownVodkaBlues_C) == 0x0001B8, "Wrong size on UINX2_CE_BrownVodkaBlues_C");

}

