#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LostTarget

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LostTarget.LostTarget_C
// 0x0000 (0x0040 - 0x0040)
class ULostTarget_C final : public UDecisionTree_LostTarget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LostTarget_C">();
	}
	static class ULostTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULostTarget_C>();
	}
};
static_assert(alignof(ULostTarget_C) == 0x000008, "Wrong alignment on ULostTarget_C");
static_assert(sizeof(ULostTarget_C) == 0x000040, "Wrong size on ULostTarget_C");

}

