#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapQuestSelectionEntry_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MapQuestSelectionEntry_BP.MapQuestSelectionEntry_BP_C
// 0x0000 (0x0330 - 0x0330)
class UMapQuestSelectionEntry_BP_C final : public UMapQuestSelectionEntryWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MapQuestSelectionEntry_BP_C">();
	}
	static class UMapQuestSelectionEntry_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMapQuestSelectionEntry_BP_C>();
	}
};
static_assert(alignof(UMapQuestSelectionEntry_BP_C) == 0x000008, "Wrong alignment on UMapQuestSelectionEntry_BP_C");
static_assert(sizeof(UMapQuestSelectionEntry_BP_C) == 0x000330, "Wrong size on UMapQuestSelectionEntry_BP_C");

}

