#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MedKitHUDAdrenoSlot_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MedKitHUDAdrenoSlot_BP.MedKitHUDAdrenoSlot_BP_C
// 0x0000 (0x0318 - 0x0318)
class UMedKitHUDAdrenoSlot_BP_C final : public UMedKitDrugSlotWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MedKitHUDAdrenoSlot_BP_C">();
	}
	static class UMedKitHUDAdrenoSlot_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMedKitHUDAdrenoSlot_BP_C>();
	}
};
static_assert(alignof(UMedKitHUDAdrenoSlot_BP_C) == 0x000008, "Wrong alignment on UMedKitHUDAdrenoSlot_BP_C");
static_assert(sizeof(UMedKitHUDAdrenoSlot_BP_C) == 0x000318, "Wrong size on UMedKitHUDAdrenoSlot_BP_C");

}

