#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeLt_ImpactHammer_AnimBP

#include "Basic.hpp"

#include "MeleeLt_ImpactHammer_AnimBP_classes.hpp"
#include "MeleeLt_ImpactHammer_AnimBP_parameters.hpp"


namespace SDK
{

// Function MeleeLt_ImpactHammer_AnimBP.MeleeLt_ImpactHammer_AnimBP_C.ExecuteUbergraph_MeleeLt_ImpactHammer_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMeleeLt_ImpactHammer_AnimBP_C::ExecuteUbergraph_MeleeLt_ImpactHammer_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MeleeLt_ImpactHammer_AnimBP_C", "ExecuteUbergraph_MeleeLt_ImpactHammer_AnimBP");

	Params::MeleeLt_ImpactHammer_AnimBP_C_ExecuteUbergraph_MeleeLt_ImpactHammer_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MeleeLt_ImpactHammer_AnimBP.MeleeLt_ImpactHammer_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UMeleeLt_ImpactHammer_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MeleeLt_ImpactHammer_AnimBP_C", "AnimGraph");

	Params::MeleeLt_ImpactHammer_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

