#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeHvy_TeleStaff_AnimBP

#include "Basic.hpp"

#include "MeleeHvy_TeleStaff_AnimBP_classes.hpp"
#include "MeleeHvy_TeleStaff_AnimBP_parameters.hpp"


namespace SDK
{

// Function MeleeHvy_TeleStaff_AnimBP.MeleeHvy_TeleStaff_AnimBP_C.ExecuteUbergraph_MeleeHvy_TeleStaff_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMeleeHvy_TeleStaff_AnimBP_C::ExecuteUbergraph_MeleeHvy_TeleStaff_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MeleeHvy_TeleStaff_AnimBP_C", "ExecuteUbergraph_MeleeHvy_TeleStaff_AnimBP");

	Params::MeleeHvy_TeleStaff_AnimBP_C_ExecuteUbergraph_MeleeHvy_TeleStaff_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MeleeHvy_TeleStaff_AnimBP.MeleeHvy_TeleStaff_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UMeleeHvy_TeleStaff_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MeleeHvy_TeleStaff_AnimBP_C", "AnimGraph");

	Params::MeleeHvy_TeleStaff_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

