#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeMod_Grip_Atk_Speed

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MeleeMod_Grip_Atk_Speed.MeleeMod_Grip_Atk_Speed_C
// 0x0000 (0x01D0 - 0x01D0)
class UMeleeMod_Grip_Atk_Speed_C final : public UMeleeGripMod
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MeleeMod_Grip_Atk_Speed_C">();
	}
	static class UMeleeMod_Grip_Atk_Speed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeleeMod_Grip_Atk_Speed_C>();
	}
};
static_assert(alignof(UMeleeMod_Grip_Atk_Speed_C) == 0x000008, "Wrong alignment on UMeleeMod_Grip_Atk_Speed_C");
static_assert(sizeof(UMeleeMod_Grip_Atk_Speed_C) == 0x0001D0, "Wrong size on UMeleeMod_Grip_Atk_Speed_C");

}

