#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeHvy_TeleStaff_TPV_Visuals

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MeleeHvy_TeleStaff_TPV_Visuals.MeleeHvy_TeleStaff_TPV_Visuals_C
// 0x0000 (0x0248 - 0x0248)
class UMeleeHvy_TeleStaff_TPV_Visuals_C final : public UPrimaryWeaponVisuals
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MeleeHvy_TeleStaff_TPV_Visuals_C">();
	}
	static class UMeleeHvy_TeleStaff_TPV_Visuals_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeleeHvy_TeleStaff_TPV_Visuals_C>();
	}
};
static_assert(alignof(UMeleeHvy_TeleStaff_TPV_Visuals_C) == 0x000008, "Wrong alignment on UMeleeHvy_TeleStaff_TPV_Visuals_C");
static_assert(sizeof(UMeleeHvy_TeleStaff_TPV_Visuals_C) == 0x000248, "Wrong size on UMeleeHvy_TeleStaff_TPV_Visuals_C");

}

