#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Sound_CanidFeral

#include "Basic.hpp"


namespace SDK::Params
{

// Function NPC_Sound_CanidFeral.NPC_Sound_CanidFeral_C.ExecuteUbergraph_NPC_Sound_CanidFeral
// 0x0004 (0x0004 - 0x0000)
struct NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral) == 0x000004, "Wrong alignment on NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral");
static_assert(sizeof(NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral) == 0x000004, "Wrong size on NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral");
static_assert(offsetof(NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral, EntryPoint) == 0x000000, "Member 'NPC_Sound_CanidFeral_C_ExecuteUbergraph_NPC_Sound_CanidFeral::EntryPoint' has a wrong offset!");

}

