#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NRayCharacterDeath

#include "Basic.hpp"

#include "NRayCharacterDeath_classes.hpp"
#include "NRayCharacterDeath_parameters.hpp"


namespace SDK
{

// Function NRayCharacterDeath.NRayCharacterDeath_C.ExecuteUbergraph_NRayCharacterDeath
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNRayCharacterDeath_C::ExecuteUbergraph_NRayCharacterDeath(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRayCharacterDeath_C", "ExecuteUbergraph_NRayCharacterDeath");

	Params::NRayCharacterDeath_C_ExecuteUbergraph_NRayCharacterDeath Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NRayCharacterDeath.NRayCharacterDeath_C.ExecuteOnReload
// (Event, Public, BlueprintEvent)
// Parameters:
// class UCharacterDeathComponent*         InDeathComponent                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNRayCharacterDeath_C::ExecuteOnReload(class UCharacterDeathComponent* InDeathComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRayCharacterDeath_C", "ExecuteOnReload");

	Params::NRayCharacterDeath_C_ExecuteOnReload Parms{};

	Parms.InDeathComponent = InDeathComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NRayCharacterDeath.NRayCharacterDeath_C.Tick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   Delta                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNRayCharacterDeath_C::Tick(float Delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRayCharacterDeath_C", "Tick");

	Params::NRayCharacterDeath_C_Tick Parms{};

	Parms.Delta = Delta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NRayCharacterDeath.NRayCharacterDeath_C.Execute
// (Event, Public, BlueprintEvent)
// Parameters:
// class UCharacterDeathComponent*         InDeathComponent                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNRayCharacterDeath_C::Execute(class UCharacterDeathComponent* InDeathComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRayCharacterDeath_C", "Execute");

	Params::NRayCharacterDeath_C_Execute Parms{};

	Parms.InDeathComponent = InDeathComponent;

	UObject::ProcessEvent(Func, &Parms);
}

}

