#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OEICommonRuntime

#include "Basic.hpp"

#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class OEICommonRuntime.OEICommonProjectSettings
// 0x0010 (0x0050 - 0x0040)
class UOEICommonProjectSettings final : public UDeveloperSettings
{
public:
	TArray<class FString>                         Packages;                                          // 0x0040(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"OEICommonProjectSettings">();
	}
	static class UOEICommonProjectSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOEICommonProjectSettings>();
	}
};
static_assert(alignof(UOEICommonProjectSettings) == 0x000008, "Wrong alignment on UOEICommonProjectSettings");
static_assert(sizeof(UOEICommonProjectSettings) == 0x000050, "Wrong size on UOEICommonProjectSettings");
static_assert(offsetof(UOEICommonProjectSettings, Packages) == 0x000040, "Member 'UOEICommonProjectSettings::Packages' has a wrong offset!");

}

