#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PQ_0002_GeothermalPasscode

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PQ_0002_GeothermalPasscode.PQ_0002_GeothermalPasscode_C
// 0x0000 (0x01D0 - 0x01D0)
class UPQ_0002_GeothermalPasscode_C final : public UQuestItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PQ_0002_GeothermalPasscode_C">();
	}
	static class UPQ_0002_GeothermalPasscode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPQ_0002_GeothermalPasscode_C>();
	}
};
static_assert(alignof(UPQ_0002_GeothermalPasscode_C) == 0x000008, "Wrong alignment on UPQ_0002_GeothermalPasscode_C");
static_assert(sizeof(UPQ_0002_GeothermalPasscode_C) == 0x0001D0, "Wrong size on UPQ_0002_GeothermalPasscode_C");

}

