#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestLogEntry_BP

#include "Basic.hpp"

#include "QuestLogEntry_BP_classes.hpp"
#include "QuestLogEntry_BP_parameters.hpp"


namespace SDK
{

// Function QuestLogEntry_BP.QuestLogEntry_BP_C.ExecuteUbergraph_QuestLogEntry_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestLogEntry_BP_C::ExecuteUbergraph_QuestLogEntry_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "ExecuteUbergraph_QuestLogEntry_BP");

	Params::QuestLogEntry_BP_C_ExecuteUbergraph_QuestLogEntry_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.OnQuestUpdateComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestLogEntry_BP_C::OnQuestUpdateComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "OnQuestUpdateComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.OnQuestUpdated
// (Event, Protected, BlueprintEvent)

void UQuestLogEntry_BP_C::OnQuestUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "OnQuestUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.FadeInTextAnimComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestLogEntry_BP_C::FadeInTextAnimComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "FadeInTextAnimComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.FadeOutTextAnimComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestLogEntry_BP_C::FadeOutTextAnimComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "FadeOutTextAnimComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.FadeOutQuestText
// (Event, Protected, BlueprintEvent)

void UQuestLogEntry_BP_C::FadeOutQuestText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "FadeOutQuestText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.FadeInQuestText
// (Event, Protected, BlueprintEvent)

void UQuestLogEntry_BP_C::FadeInQuestText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "FadeInQuestText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.OnQuestFailed
// (Event, Protected, BlueprintEvent)

void UQuestLogEntry_BP_C::OnQuestFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "OnQuestFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.OnQuestCompleted
// (Event, Protected, BlueprintEvent)

void UQuestLogEntry_BP_C::OnQuestCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "OnQuestCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.QuestAnimComplete
// (BlueprintCallable, BlueprintEvent)

void UQuestLogEntry_BP_C::QuestAnimComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "QuestAnimComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestLogEntry_BP.QuestLogEntry_BP_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UQuestLogEntry_BP_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestLogEntry_BP_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

