#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RangedMod_Barrel_Accuracy

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RangedMod_Barrel_Accuracy.RangedMod_Barrel_Accuracy_C
// 0x0000 (0x01D0 - 0x01D0)
class URangedMod_Barrel_Accuracy_C final : public URangedBarrelMod
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RangedMod_Barrel_Accuracy_C">();
	}
	static class URangedMod_Barrel_Accuracy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URangedMod_Barrel_Accuracy_C>();
	}
};
static_assert(alignof(URangedMod_Barrel_Accuracy_C) == 0x000008, "Wrong alignment on URangedMod_Barrel_Accuracy_C");
static_assert(sizeof(URangedMod_Barrel_Accuracy_C) == 0x0001D0, "Wrong size on URangedMod_Barrel_Accuracy_C");

}

