#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RBT_SentryBot_AnimBlueprint

#include "Basic.hpp"

#include "Indiana_structs.hpp"
#include "Indiana_classes.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "CombatEnum_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass RBT_SentryBot_AnimBlueprint.RBT_SentryBot_AnimBlueprint_C
// 0x29F0 (0x33D0 - 0x09E0)
class URBT_SentryBot_AnimBlueprint_C final : public UQuadrupedAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x09E8(0x0030)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_7;                              // 0x0A18(0x0048)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x0A60(0x0108)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x0B68(0x00C0)()
	uint8                                         Pad_C28[0x8];                                      // 0x0C28(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_EyeLookAt                    AnimGraphNode_EyeLookAt;                           // 0x0C30(0x01C0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x0DF0(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_6;                              // 0x0E70(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x0EB8(0x00A0)()
	struct FAnimNode_LegIK                        AnimGraphNode_LegIK_2;                             // 0x0F58(0x00F8)()
	struct FAnimNode_LegIK                        AnimGraphNode_LegIK_1;                             // 0x1050(0x00F8)()
	struct FAnimNode_LegIK                        AnimGraphNode_LegIK;                               // 0x1148(0x00F8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_5;                              // 0x1240(0x0048)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x1288(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x12A8(0x00A0)()
	struct FAnimNode_PoseSnapshot                 AnimGraphNode_PoseSnapshot;                        // 0x1348(0x0090)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_4;                              // 0x13D8(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x1420(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x1448(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x1490(0x0048)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x14D8(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x14F8(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x1598(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x15C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x15E8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1610(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x1690(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x16C0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x1740(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x1770(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x1798(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x17C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x17E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x1810(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x1838(0x0028)()
	struct FAnimNode_LocomotionPlay               AnimGraphNode_LocomotionPlay_3;                    // 0x1860(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x18F0(0x0030)()
	struct FAnimNode_LocomotionPlay               AnimGraphNode_LocomotionPlay_2;                    // 0x1920(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x19B0(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x19E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x1A08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x1A30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x1A58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x1A80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x1AA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1AD0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x1AF8(0x0028)()
	struct FAnimNode_RandomSequenceNamed          AnimGraphNode_RandomSequenceNamed_1;               // 0x1B20(0x0088)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x1BA8(0x0030)()
	struct FAnimNode_RandomSequenceNamed          AnimGraphNode_RandomSequenceNamed;                 // 0x1BD8(0x0088)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x1C60(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x1C90(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x1D10(0x00A0)()
	struct FAnimNode_RandomPlayer                 AnimGraphNode_RandomPlayer;                        // 0x1DB0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x1E30(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x1E60(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1F10(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x1F40(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1FF0(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x2020(0x00B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x20D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x20F8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x2120(0x0080)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x21A0(0x00B0)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x2250(0x00F0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x2340(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x2370(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x2398(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x23C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x23E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x2410(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x2438(0x0028)()
	struct FAnimNode_LocomotionPlay               AnimGraphNode_LocomotionPlay_1;                    // 0x2460(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x24F0(0x0030)()
	struct FAnimNode_LocomotionPlay               AnimGraphNode_LocomotionPlay;                      // 0x2520(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x25B0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x25E0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x2660(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x2690(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x2740(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x2770(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x2820(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x2850(0x00B0)()
	struct FAnimNode_RefPose                      AnimGraphNode_LocalRefPose;                        // 0x2900(0x0018)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x2918(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x2A20(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x2B28(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x2B50(0x0048)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x2B98(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x2BB8(0x0020)()
	struct FAnimNode_BatchJointDriver             AnimGraphNode_BatchJointDriver;                    // 0x2BD8(0x01E0)()
	struct FAnimNode_RotateBoneAboutBone          AnimGraphNode_RotateBoneAboutBone;                 // 0x2DB8(0x0100)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x2EB8(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x3010(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x3038(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x3060(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x3120(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x3168(0x0158)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x32C0(0x00C8)()
	class USentryBot_MachineGun_WeaponAnimations_C* WeaponAnimationsBP;                                // 0x3388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECombatEnum                                   CombatEnum;                                        // 0x3390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3391[0x3];                                     // 0x3391(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HitReactionDirection;                              // 0x3394(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HitReactionRate;                                   // 0x3398(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHitReactType                                 HitReactionType;                                   // 0x339C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_339D[0x3];                                     // 0x339D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HitReactionActive;                                 // 0x33A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LeftFootStrength;                                  // 0x33A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RightFootStrength;                                 // 0x33A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FrontFootStrength;                                 // 0x33AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsConstruction;                                   // 0x33B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33B1[0x3];                                     // 0x33B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DrillSpeed;                                        // 0x33B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DrillSpinAngle;                                    // 0x33B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DrillActive;                                       // 0x33BC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33BD[0x3];                                     // 0x33BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LegIKAlphaSwitch;                                  // 0x33C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_RBT_SentryBot_AnimBlueprint(int32 EntryPoint);
	void AnimNotify_IKOff();
	void AnimNotify_StopDrill();
	void AnimNotify_StartDrill();
	void OnNewWeaponAnimations(class UWeaponAnimations* NewWeaponAnimations);
	void OnNewWeaponAnimationSet();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void OnRebuildAnimationSetData();
	void NeutralTransition();
	void CombatTransition();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_RBT_SentryBot_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_2D9C98D94892E07C54913C9AECAA42CD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_RBT_SentryBot_AnimBlueprint_AnimGraphNode_ModifyBone_66C75ABA4C34FFD80B0D00B6D5E3E230();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_RBT_SentryBot_AnimBlueprint_AnimGraphNode_ModifyBone_025E53A0414B7F52C13FA188110B239A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_RBT_SentryBot_AnimBlueprint_AnimGraphNode_ModifyBone_529EE55E45DFFDBB510E57ABA42FC99A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_RBT_SentryBot_AnimBlueprint_AnimGraphNode_RotateBoneAboutBone_AB64ACD64233BBF704972BB566194F19();
	void CheckHitFlinches();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RBT_SentryBot_AnimBlueprint_C">();
	}
	static class URBT_SentryBot_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URBT_SentryBot_AnimBlueprint_C>();
	}
};
static_assert(alignof(URBT_SentryBot_AnimBlueprint_C) == 0x000010, "Wrong alignment on URBT_SentryBot_AnimBlueprint_C");
static_assert(sizeof(URBT_SentryBot_AnimBlueprint_C) == 0x0033D0, "Wrong size on URBT_SentryBot_AnimBlueprint_C");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, UberGraphFrame) == 0x0009E0, "Member 'URBT_SentryBot_AnimBlueprint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Root) == 0x0009E8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_7) == 0x000A18, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_7' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_ModifyBone_2) == 0x000A60, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LayeredBoneBlend_1) == 0x000B68, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_EyeLookAt) == 0x000C30, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_EyeLookAt' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer_5) == 0x000DF0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_6) == 0x000E70, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_6' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendListByBool_3) == 0x000EB8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LegIK_2) == 0x000F58, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LegIK_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LegIK_1) == 0x001050, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LegIK_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LegIK) == 0x001148, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LegIK' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_5) == 0x001240, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_5' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x001288, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendListByBool_2) == 0x0012A8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_PoseSnapshot) == 0x001348, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_PoseSnapshot' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_4) == 0x0013D8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_4' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_UseCachedPose_3) == 0x001420, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_3) == 0x001448, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_2) == 0x001490, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocalToComponentSpace_1) == 0x0014D8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendListByBool_1) == 0x0014F8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_24) == 0x001598, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_23) == 0x0015C0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_22) == 0x0015E8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer_4) == 0x001610, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_14) == 0x001690, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer_3) == 0x0016C0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_13) == 0x001740, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_21) == 0x001770, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_20) == 0x001798, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_19) == 0x0017C0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_18) == 0x0017E8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_17) == 0x001810, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_16) == 0x001838, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocomotionPlay_3) == 0x001860, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocomotionPlay_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_12) == 0x0018F0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocomotionPlay_2) == 0x001920, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocomotionPlay_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_11) == 0x0019B0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_15) == 0x0019E0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_14) == 0x001A08, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_13) == 0x001A30, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_12) == 0x001A58, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_11) == 0x001A80, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_10) == 0x001AA8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_9) == 0x001AD0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_8) == 0x001AF8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_RandomSequenceNamed_1) == 0x001B20, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_RandomSequenceNamed_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_10) == 0x001BA8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_RandomSequenceNamed) == 0x001BD8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_RandomSequenceNamed' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_9) == 0x001C60, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer_2) == 0x001C90, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendListByBool) == 0x001D10, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_RandomPlayer) == 0x001DB0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_RandomPlayer' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_8) == 0x001E30, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine_5) == 0x001E60, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_7) == 0x001F10, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine_4) == 0x001F40, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine_4' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_6) == 0x001FF0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine_3) == 0x002020, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_7) == 0x0020D0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_6) == 0x0020F8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer_1) == 0x002120, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendListByEnum) == 0x0021A0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BlendSpacePlayer) == 0x002250, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_5) == 0x002340, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_5) == 0x002370, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_4) == 0x002398, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_3) == 0x0023C0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_2) == 0x0023E8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult_1) == 0x002410, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TransitionResult) == 0x002438, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocomotionPlay_1) == 0x002460, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocomotionPlay_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_4) == 0x0024F0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocomotionPlay) == 0x002520, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocomotionPlay' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_3) == 0x0025B0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SequencePlayer) == 0x0025E0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_2) == 0x002660, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine_2) == 0x002690, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult_1) == 0x002740, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine_1) == 0x002770, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateResult) == 0x002820, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_StateMachine) == 0x002850, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocalRefPose) == 0x002900, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocalRefPose' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_ModifyBone_1) == 0x002918, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_ModifyBone) == 0x002A20, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_UseCachedPose_2) == 0x002B28, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot_1) == 0x002B50, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_ComponentToLocalSpace) == 0x002B98, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LocalToComponentSpace) == 0x002BB8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_BatchJointDriver) == 0x002BD8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_BatchJointDriver' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_RotateBoneAboutBone) == 0x002DB8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_RotateBoneAboutBone' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SaveCachedPose_1) == 0x002EB8, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_UseCachedPose_1) == 0x003010, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_UseCachedPose) == 0x003038, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_LayeredBoneBlend) == 0x003060, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_Slot) == 0x003120, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_SaveCachedPose) == 0x003168, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, AnimGraphNode_TwoWayBlend) == 0x0032C0, "Member 'URBT_SentryBot_AnimBlueprint_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, WeaponAnimationsBP) == 0x003388, "Member 'URBT_SentryBot_AnimBlueprint_C::WeaponAnimationsBP' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, CombatEnum) == 0x003390, "Member 'URBT_SentryBot_AnimBlueprint_C::CombatEnum' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, HitReactionDirection) == 0x003394, "Member 'URBT_SentryBot_AnimBlueprint_C::HitReactionDirection' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, HitReactionRate) == 0x003398, "Member 'URBT_SentryBot_AnimBlueprint_C::HitReactionRate' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, HitReactionType) == 0x00339C, "Member 'URBT_SentryBot_AnimBlueprint_C::HitReactionType' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, HitReactionActive) == 0x0033A0, "Member 'URBT_SentryBot_AnimBlueprint_C::HitReactionActive' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, LeftFootStrength) == 0x0033A4, "Member 'URBT_SentryBot_AnimBlueprint_C::LeftFootStrength' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, RightFootStrength) == 0x0033A8, "Member 'URBT_SentryBot_AnimBlueprint_C::RightFootStrength' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, FrontFootStrength) == 0x0033AC, "Member 'URBT_SentryBot_AnimBlueprint_C::FrontFootStrength' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, bIsConstruction) == 0x0033B0, "Member 'URBT_SentryBot_AnimBlueprint_C::bIsConstruction' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, DrillSpeed) == 0x0033B4, "Member 'URBT_SentryBot_AnimBlueprint_C::DrillSpeed' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, DrillSpinAngle) == 0x0033B8, "Member 'URBT_SentryBot_AnimBlueprint_C::DrillSpinAngle' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, DrillActive) == 0x0033BC, "Member 'URBT_SentryBot_AnimBlueprint_C::DrillActive' has a wrong offset!");
static_assert(offsetof(URBT_SentryBot_AnimBlueprint_C, LegIKAlphaSwitch) == 0x0033C0, "Member 'URBT_SentryBot_AnimBlueprint_C::LegIKAlphaSwitch' has a wrong offset!");

}

