#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsMenuButtonSlot_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SettingsMenuButtonSlot_BP.SettingsMenuButtonSlot_BP_C
// 0x0000 (0x0350 - 0x0350)
class USettingsMenuButtonSlot_BP_C final : public USettingsMenuButtonSlotWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SettingsMenuButtonSlot_BP_C">();
	}
	static class USettingsMenuButtonSlot_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USettingsMenuButtonSlot_BP_C>();
	}
};
static_assert(alignof(USettingsMenuButtonSlot_BP_C) == 0x000008, "Wrong alignment on USettingsMenuButtonSlot_BP_C");
static_assert(sizeof(USettingsMenuButtonSlot_BP_C) == 0x000350, "Wrong size on USettingsMenuButtonSlot_BP_C");

}

