#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimpleContainer_BP

#include "Basic.hpp"

#include "SimpleContainer_BP_classes.hpp"
#include "SimpleContainer_BP_parameters.hpp"


namespace SDK
{

// Function SimpleContainer_BP.SimpleContainer_BP_C.ExecuteUbergraph_SimpleContainer_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASimpleContainer_BP_C::ExecuteUbergraph_SimpleContainer_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "ExecuteUbergraph_SimpleContainer_BP");

	Params::SimpleContainer_BP_C_ExecuteUbergraph_SimpleContainer_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.OnPlayerOpenedContainer_Event_0
// (BlueprintCallable, BlueprintEvent)

void ASimpleContainer_BP_C::OnPlayerOpenedContainer_Event_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "OnPlayerOpenedContainer_Event_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_1_ItemStackDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FItemStack                       Item                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)

void ASimpleContainer_BP_C::BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_1_ItemStackDelegate__DelegateSignature(const struct FItemStack& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_1_ItemStackDelegate__DelegateSignature");

	Params::SimpleContainer_BP_C_BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_1_ItemStackDelegate__DelegateSignature Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_0_ItemStackDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// struct FItemStack                       Item                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)

void ASimpleContainer_BP_C::BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_0_ItemStackDelegate__DelegateSignature(const struct FItemStack& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_0_ItemStackDelegate__DelegateSignature");

	Params::SimpleContainer_BP_C_BndEvt__InventoryComponent_K2Node_ComponentBoundEvent_0_ItemStackDelegate__DelegateSignature Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.AnimateLid__UpdateFunc
// (BlueprintEvent)

void ASimpleContainer_BP_C::AnimateLid__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "AnimateLid__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.AnimateLid__FinishedFunc
// (BlueprintEvent)

void ASimpleContainer_BP_C::AnimateLid__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "AnimateLid__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.GetLightingConfig
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMeshComponent*             Mesh                                                   (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             MaterialSlot                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASimpleContainer_BP_C::GetLightingConfig(class UStaticMeshComponent** Mesh, class FName* MaterialSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "GetLightingConfig");

	Params::SimpleContainer_BP_C_GetLightingConfig Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Mesh != nullptr)
		*Mesh = Parms.Mesh;

	if (MaterialSlot != nullptr)
		*MaterialSlot = Parms.MaterialSlot;
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.ApplyLight
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASimpleContainer_BP_C::ApplyLight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "ApplyLight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.OnStateChanged
// (Public, BlueprintCallable, BlueprintEvent)

void ASimpleContainer_BP_C::OnStateChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "OnStateChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASimpleContainer_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.OnAnimateClose
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IgnoreSound_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InstantAnimation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASimpleContainer_BP_C::OnAnimateClose(bool IgnoreSound_0, bool InstantAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "OnAnimateClose");

	Params::SimpleContainer_BP_C_OnAnimateClose Parms{};

	Parms.IgnoreSound_0 = IgnoreSound_0;
	Parms.InstantAnimation = InstantAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.OnAnimateOpen
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InstantAnimation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASimpleContainer_BP_C::OnAnimateOpen(bool InstantAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "OnAnimateOpen");

	Params::SimpleContainer_BP_C_OnAnimateOpen Parms{};

	Parms.InstantAnimation = InstantAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SimpleContainer_BP.SimpleContainer_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASimpleContainer_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SimpleContainer_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

