#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SlidingDoor_IntA_BP

#include "Basic.hpp"

#include "SlidingDoor_Int_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SlidingDoor_IntA_BP.SlidingDoor_IntA_BP_C
// 0x0000 (0x0590 - 0x0590)
class ASlidingDoor_IntA_BP_C final : public ASlidingDoor_Int_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SlidingDoor_IntA_BP_C">();
	}
	static class ASlidingDoor_IntA_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASlidingDoor_IntA_BP_C>();
	}
};
static_assert(alignof(ASlidingDoor_IntA_BP_C) == 0x000008, "Wrong alignment on ASlidingDoor_IntA_BP_C");
static_assert(sizeof(ASlidingDoor_IntA_BP_C) == 0x000590, "Wrong size on ASlidingDoor_IntA_BP_C");

}

