#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatsSkillsPage_BP

#include "Basic.hpp"

#include "StatsSkillsPage_BP_classes.hpp"
#include "StatsSkillsPage_BP_parameters.hpp"


namespace SDK
{

// Function StatsSkillsPage_BP.StatsSkillsPage_BP_C.Get_SkillGroupScrollBox_bIsEnabled_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UStatsSkillsPage_BP_C::Get_SkillGroupScrollBox_bIsEnabled_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StatsSkillsPage_BP_C", "Get_SkillGroupScrollBox_bIsEnabled_0");

	Params::StatsSkillsPage_BP_C_Get_SkillGroupScrollBox_bIsEnabled_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

