#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: T_Lab_CleanupCrew

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass T_Lab_CleanupCrew.T_Lab_CleanupCrew_C
// 0x0000 (0x0238 - 0x0238)
class UT_Lab_CleanupCrew_C final : public UTeamData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"T_Lab_CleanupCrew_C">();
	}
	static class UT_Lab_CleanupCrew_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UT_Lab_CleanupCrew_C>();
	}
};
static_assert(alignof(UT_Lab_CleanupCrew_C) == 0x000008, "Wrong alignment on UT_Lab_CleanupCrew_C");
static_assert(sizeof(UT_Lab_CleanupCrew_C) == 0x000238, "Wrong size on UT_Lab_CleanupCrew_C");

}

