#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThirstSpell_T4

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ThirstSpell_T4.ThirstSpell_T4_C
// 0x0000 (0x0190 - 0x0190)
class UThirstSpell_T4_C final : public USpell
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ThirstSpell_T4_C">();
	}
	static class UThirstSpell_T4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UThirstSpell_T4_C>();
	}
};
static_assert(alignof(UThirstSpell_T4_C) == 0x000010, "Wrong alignment on UThirstSpell_T4_C");
static_assert(sizeof(UThirstSpell_T4_C) == 0x000190, "Wrong size on UThirstSpell_T4_C");

}

