#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Townie_03_Var2

#include "Basic.hpp"

#include "Armor_Townie_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Townie_03_Var2.Townie_03_Var2_C
// 0x0000 (0x0370 - 0x0370)
class UTownie_03_Var2_C final : public UArmor_Townie_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Townie_03_Var2_C">();
	}
	static class UTownie_03_Var2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTownie_03_Var2_C>();
	}
};
static_assert(alignof(UTownie_03_Var2_C) == 0x000008, "Wrong alignment on UTownie_03_Var2_C");
static_assert(sizeof(UTownie_03_Var2_C) == 0x000370, "Wrong size on UTownie_03_Var2_C");

}

