#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TTDStatusEffectsWidget_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TTDStatusEffectsWidget_BP.TTDStatusEffectsWidget_BP_C
// 0x0008 (0x0320 - 0x0318)
class UTTDStatusEffectsWidget_BP_C final : public UTTDStatusEffectsWidget
{
public:
	class UStatusEffectTagEntry_BP_C*             StatusEffectTagEntry_BP;                           // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TTDStatusEffectsWidget_BP_C">();
	}
	static class UTTDStatusEffectsWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTTDStatusEffectsWidget_BP_C>();
	}
};
static_assert(alignof(UTTDStatusEffectsWidget_BP_C) == 0x000008, "Wrong alignment on UTTDStatusEffectsWidget_BP_C");
static_assert(sizeof(UTTDStatusEffectsWidget_BP_C) == 0x000320, "Wrong size on UTTDStatusEffectsWidget_BP_C");
static_assert(offsetof(UTTDStatusEffectsWidget_BP_C, StatusEffectTagEntry_BP) == 0x000318, "Member 'UTTDStatusEffectsWidget_BP_C::StatusEffectTagEntry_BP' has a wrong offset!");

}

