#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TutorialPopupWidget_BP

#include "Basic.hpp"

#include "Indiana_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TutorialPopupWidget_BP.TutorialPopupWidget_BP_C
// 0x0010 (0x0360 - 0x0350)
class UTutorialPopupWidget_BP_C final : public UTutorialPopupWidget
{
public:
	class UTutorialPopupStyle_Corporate_BP_C*     TutorialPopupStyle_Corporate_BP;                   // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTutorialPopupStyle_Simple_BP_C*        TutorialPopupStyle_Simple_BP;                      // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TutorialPopupWidget_BP_C">();
	}
	static class UTutorialPopupWidget_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorialPopupWidget_BP_C>();
	}
};
static_assert(alignof(UTutorialPopupWidget_BP_C) == 0x000008, "Wrong alignment on UTutorialPopupWidget_BP_C");
static_assert(sizeof(UTutorialPopupWidget_BP_C) == 0x000360, "Wrong size on UTutorialPopupWidget_BP_C");
static_assert(offsetof(UTutorialPopupWidget_BP_C, TutorialPopupStyle_Corporate_BP) == 0x000350, "Member 'UTutorialPopupWidget_BP_C::TutorialPopupStyle_Corporate_BP' has a wrong offset!");
static_assert(offsetof(UTutorialPopupWidget_BP_C, TutorialPopupStyle_Simple_BP) == 0x000358, "Member 'UTutorialPopupWidget_BP_C::TutorialPopupStyle_Simple_BP' has a wrong offset!");

}

