#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VideoScreen_ShipAI

#include "Basic.hpp"

#include "VideoScreen_ShipAI_classes.hpp"
#include "VideoScreen_ShipAI_parameters.hpp"


namespace SDK
{

// Function VideoScreen_ShipAI.VideoScreen_ShipAI_C.ConversationStarted
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Speaker                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGuid                            Guid                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NodeID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UVideoScreen_ShipAI_C::ConversationStarted(class AActor* Speaker, const struct FGuid& Guid, int32 NodeID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoScreen_ShipAI_C", "ConversationStarted");

	Params::VideoScreen_ShipAI_C_ConversationStarted Parms{};

	Parms.Speaker = Speaker;
	Parms.Guid = std::move(Guid);
	Parms.NodeID = NodeID;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VideoScreen_ShipAI.VideoScreen_ShipAI_C.ConversationEnded
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGuid                            Guid                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UVideoScreen_ShipAI_C::ConversationEnded(const struct FGuid& Guid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoScreen_ShipAI_C", "ConversationEnded");

	Params::VideoScreen_ShipAI_C_ConversationEnded Parms{};

	Parms.Guid = std::move(Guid);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VideoScreen_ShipAI.VideoScreen_ShipAI_C.ConversationNodeChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Camera                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Audio                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NodeID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UVideoScreen_ShipAI_C::ConversationNodeChanged(class AActor* Character, class AActor* Camera, class AActor* Audio, int32 NodeID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoScreen_ShipAI_C", "ConversationNodeChanged");

	Params::VideoScreen_ShipAI_C_ConversationNodeChanged Parms{};

	Parms.Character = Character;
	Parms.Camera = Camera;
	Parms.Audio = Audio;
	Parms.NodeID = NodeID;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VideoScreen_ShipAI.VideoScreen_ShipAI_C.Play_Screen_On
// (Public, BlueprintCallable, BlueprintEvent)

void UVideoScreen_ShipAI_C::Play_Screen_On()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoScreen_ShipAI_C", "Play_Screen_On");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VideoScreen_ShipAI.VideoScreen_ShipAI_C.Play_Screen_Off
// (Public, BlueprintCallable, BlueprintEvent)

void UVideoScreen_ShipAI_C::Play_Screen_Off()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoScreen_ShipAI_C", "Play_Screen_Off");

	UObject::ProcessEvent(Func, nullptr);
}

}

