#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponRadialBackgroundSection_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function WeaponRadialBackgroundSection_BP.WeaponRadialBackgroundSection_BP_C.ExecuteUbergraph_WeaponRadialBackgroundSection_BP
// 0x0008 (0x0008 - 0x0000)
struct WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue;       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP) == 0x000004, "Wrong alignment on WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP");
static_assert(sizeof(WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP) == 0x000008, "Wrong size on WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP");
static_assert(offsetof(WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP, EntryPoint) == 0x000000, "Member 'WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP, CallFunc_NearlyEqual_FloatFloat_ReturnValue) == 0x000004, "Member 'WeaponRadialBackgroundSection_BP_C_ExecuteUbergraph_WeaponRadialBackgroundSection_BP::CallFunc_NearlyEqual_FloatFloat_ReturnValue' has a wrong offset!");

}

