#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero0_FirstShipTakeOff

#include "Basic.hpp"

#include "Zero0_FirstShipTakeOff_classes.hpp"
#include "Zero0_FirstShipTakeOff_parameters.hpp"


namespace SDK
{

// Function 00_FirstShipTakeOff.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.NS_Thruster_Trail_L_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_L                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bNewActive                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bReset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::NS_Thruster_Trail_L_Event_0(class ANiagaraActor* NS_Thruster_Trail_L, bool bNewActive, bool bReset, class FName Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "NS_Thruster_Trail_L_Event_0");

	Params::SequenceDirector_C_NS_Thruster_Trail_L_Event_0 Parms{};

	Parms.NS_Thruster_Trail_L = NS_Thruster_Trail_L;
	Parms.bNewActive = bNewActive;
	Parms.bReset = bReset;
	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.NS_Thruster_Trail_R_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_R                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bNewActive                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bReset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::NS_Thruster_Trail_R_Event_0(class ANiagaraActor* NS_Thruster_Trail_R, bool bNewActive, bool bReset, class FName Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "NS_Thruster_Trail_R_Event_0");

	Params::SequenceDirector_C_NS_Thruster_Trail_R_Event_0 Parms{};

	Parms.NS_Thruster_Trail_R = NS_Thruster_Trail_R;
	Parms.bNewActive = bNewActive;
	Parms.bReset = bReset;
	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.NS_Thruster_Trail_Main_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_Main                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bNewActive                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bReset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::NS_Thruster_Trail_Main_Event_0(class ANiagaraActor* NS_Thruster_Trail_Main, bool bNewActive, bool bReset, class FName Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "NS_Thruster_Trail_Main_Event_0");

	Params::SequenceDirector_C_NS_Thruster_Trail_Main_Event_0 Parms{};

	Parms.NS_Thruster_Trail_Main = NS_Thruster_Trail_Main;
	Parms.bNewActive = bNewActive;
	Parms.bReset = bReset;
	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_Main                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class ANiagaraActor* NS_Thruster_Trail_Main)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.NS_Thruster_Trail_Main = NS_Thruster_Trail_Main;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_Main                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_1(class ANiagaraActor* NS_Thruster_Trail_Main)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_1");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1 Parms{};

	Parms.NS_Thruster_Trail_Main = NS_Thruster_Trail_Main;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_2
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_R                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_2(class ANiagaraActor* NS_Thruster_Trail_R)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_2");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_2 Parms{};

	Parms.NS_Thruster_Trail_R = NS_Thruster_Trail_R;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_3
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_R                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_3(class ANiagaraActor* NS_Thruster_Trail_R)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_3");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_3 Parms{};

	Parms.NS_Thruster_Trail_R = NS_Thruster_Trail_R;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_4
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_L                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_4(class ANiagaraActor* NS_Thruster_Trail_L)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_4");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_4 Parms{};

	Parms.NS_Thruster_Trail_L = NS_Thruster_Trail_L;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_FirstShipTakeOff.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_5
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANiagaraActor*                    NS_Thruster_Trail_L                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_5(class ANiagaraActor* NS_Thruster_Trail_L)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_5");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_5 Parms{};

	Parms.NS_Thruster_Trail_L = NS_Thruster_Trail_L;

	UObject::ProcessEvent(Func, &Parms);
}

}

